services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/canicoif
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    container_name: mongo
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always